version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: go2super-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
#      # Usuario y contraseña del administrador
#      MONGO_INITDB_ROOT_USERNAME: admin
#      MONGO_INITDB_ROOT_PASSWORD: admin123
#      # Base de datos inicial (opcional)
      MONGO_INITDB_DATABASE: go2super
    volumes:
      # Persistir datos en tu máquina local
      - mongodb_data:/data/db
      # Persistir configuración
      - mongodb_config:/data/configdb
    networks:
      - go2super-network

  # Opcional: Mongo Express (Interfaz web para administrar MongoDB)
  mongo-express:
    image: mongo-express:latest
    container_name: go2super-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - go2super-network

# Volúmenes persistentes
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

# Red para los servicios
networks:
  go2super-network:
    driver: bridge